name: Call a reusable workflow and use its outputs

on:
  pull_request

jobs:
  job1:
    uses: ./.github/workflows/output-files.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }}
