
name: file change detect
on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ","
      - run: echo "${{ steps.file_changes.outputs.files }}"
