name: test by action cloudbuild
on:
  workflow_dispatch:
    inputs:
      appenv:
        description: appenv var i.e staging, qa
        required: true

jobs:
  downloadasset:
    runs-on: ubuntu-latest
    steps:
    - uses: robinraju/release-downloader@v1.4
      with:
        latest: true
        tarBall: true
        zipBall: true

      - name: create version file 
        run: |
          touch version
          echo "${{ env.LAST_TAG }}" >> version

          cat version
      
      - name: create notes file 
        run: |
          touch notes.txt
          NOTES=$(curl --silent  "${{env.RELEASE_URL}}" | \
           jq --raw-output '.[0].body')
          echo "${NOTES}" >> notes.txt

          cat notes.txt