on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update the tag
        uses: julb/action-manage-tag@v1
        with:
          name: tag-name
          state: present
          from: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: checj ref
        run: echo ${{ github.ref }}
