name: Release new CLI versions
on:
  push:
    tags:
      - '*'

env:
 TAG_URL: https://api.github.com/repos/mollypi/repo-dispatch/tags

jobs:
  release-new-cli:
    name: Release new CLI versions
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      

      - name: get latest tag
        run: |- 
          TAG=$(curl --silent  "${{env.TAG_URL}}" | \
           jq --raw-output '.[0].name')
          echo "LAST_TAG=${LAST_TAG}" >> $GITHUB_ENV

      - name: debug
        run: echo ${env.LAST_TAG}