name: Repository Dispatch
on:
  repository_dispatch:
    types:
      - my-event
jobs:
  myEvent:
    runs-on: ubuntu-latest
    env:
      STUFF: '${{ github.event.client_payload.version }}'
    steps:
      - name: test
        run: echo $STUFF
