name: test-ansible

on:
  workflow_dispatch
  
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: installl netdata
        run: bash <(curl -Ss https://my-netdata.io/kickstart.sh)
        shell: bash
