name: test-ansible

on:
  workflow_dispatch
  
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: is ansible present?
        run: ansible --version
      
      - name: import from galaxy
        run: ansible-galaxy collection install community.google
