on:
  issue_comment:
    types:
    - created

jobs:
  runjob:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code 
      uses: actions/checkout@v2

    - name: Sets env vars for release
      run: |
        echo "appenv=production" >> $GITHUB_ENV
      if: github.event.comment.body == '/deployproduction'

    - name: default vars to stage 
      run: echo "appenv=staging" >> $GITHUB_ENV
      
    - name: debug stuff
      run: echo "GITHUB_SHA: ${GITHUB_SHA}"

