
   
on:
  pull_request
  
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: JoseThen/comment-pr@v1.1.1
      with:
        comment: 'This PR is the bees knees!'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
