on:
  issue_comment:
    types:
    - created

jobs:
  runjob:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code 
        uses: actions/checkout@v2
      
      - name: get short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: debug output 
        run: echo ${{ steps.short-sha.outputs.sha }}
      
      - name: use output
        run: echo 'stage-${{ steps.short-sha.outputs.sha }}'
