on:
  issue_comment:
    types:
    - created

jobs:
  runjob:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code 
        uses: actions/checkout@v2
      
      - name: Get tag
        id: tag
        run: echo "::set-output name=latesttag::$(git describe --tags --abbrev=0)"

      - name: Use tag
        run: echo ${{ steps.tag.outputs.latesttag }}
